import { StyleSheet } from 'react-native';
import { Fonts } from '../../../theme/fonts';
import { pt } from '../../../theme/tokens';

export const ICON = {
  status: 24,
  bullet: 17,
  meta: 16,
  chip: 12,
  cta: 16,
  ghost: 16,
};

export const DISC = {
  status: 52,
  bullet: 38,
  meta: 38,
};

export const STATUS_COLORS = {
  canvas: '#FAF8F5',
  card: '#FFFFFF',
  cardBorder: '#EFE8DE',
  cardBorderSubtle: '#F4EFE6',
  darkGreen: '#1B4332',
  darkGreenSoft: '#2D6A4F',
  ink: '#1A1A1A',
  inkSecondary: '#4A4D55',
  inkMuted: '#7A7D85',
  inkFaint: '#A0A3AA',
  gold: '#C5A869',
  well: '#F7F5F0',
  wellBorder: '#EDE7DC',
  divider: '#F0ECE5',

  // Danger / Failed
  danger: '#D32F2F',
  dangerDiscBg: '#FDF2F2',
  dangerDiscBorder: '#FED7D7',
  dangerPillBg: '#FDEAEA',
  dangerPillBorder: '#FED7D7',
  dangerPillText: '#C53030',
  dangerAlertBg: '#FFF5F5',
  dangerAlertBorder: '#FED7D7',
  dangerAlertText: '#9B2C2C',

  // Success
  success: '#1F7D4E',
  successDiscBg: '#EBF7EE',
  successDiscBorder: '#D1EFE0',
  successPillBg: '#EAF7F0',
  successPillBorder: '#C6ECCF',
  successPillText: '#1F7D4E',

  // Pending
  pending: '#B27B17',
  pendingDiscBg: '#FFF7E8',
  pendingDiscBorder: '#FDE6BA',
  pendingPillBg: '#FFF7E8',
  pendingPillBorder: '#FDE6BA',
  pendingPillText: '#B27B17',
};

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: STATUS_COLORS.canvas,
  },

  safeTop: {
    backgroundColor: '#FFFFFF',
  },

  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: STATUS_COLORS.cardBorder,
  },
  topBarBack: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: STATUS_COLORS.cardBorder,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 1,
  },
  topBarCopy: {
    flex: 1,
    marginLeft: 12,
    marginRight: 8,
  },
  topBarTitle: {
    fontFamily: Fonts.cormorantGaramond.semiBold,
    fontSize: pt(21),
    lineHeight: pt(25),
    color: STATUS_COLORS.ink,
    letterSpacing: -0.3,
  },
  topBarSubtitle: {
    fontFamily: Fonts.lexend.regular,
    fontSize: pt(11),
    lineHeight: pt(15),
    color: STATUS_COLORS.inkMuted,
    marginTop: 2,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4.5,
    backgroundColor: STATUS_COLORS.well,
    borderColor: STATUS_COLORS.wellBorder,
  },
  statusPillDanger: {
    backgroundColor: STATUS_COLORS.dangerPillBg,
    borderColor: STATUS_COLORS.dangerPillBorder,
  },
  statusPillSuccess: {
    backgroundColor: STATUS_COLORS.successPillBg,
    borderColor: STATUS_COLORS.successPillBorder,
  },
  statusPillBrand: {
    backgroundColor: STATUS_COLORS.pendingPillBg,
    borderColor: STATUS_COLORS.pendingPillBorder,
  },
  statusPillText: {
    fontFamily: Fonts.lexend.semiBold,
    fontSize: pt(10),
    letterSpacing: 0.8,
    color: STATUS_COLORS.inkSecondary,
  },
  statusPillTextDanger: {
    color: STATUS_COLORS.dangerPillText,
  },
  statusPillTextSuccess: {
    color: STATUS_COLORS.successPillText,
  },
  statusPillTextBrand: {
    color: STATUS_COLORS.pendingPillText,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },

  scrollContent: {
    paddingTop: 12,
    paddingBottom: 28,
  },
  section: {
    marginTop: 12,
    marginHorizontal: 16,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: STATUS_COLORS.cardBorder,
    backgroundColor: STATUS_COLORS.card,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 1,
  },
  card: {
    padding: 18,
  },
  cardContainer: {
    backgroundColor: STATUS_COLORS.card,
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: STATUS_COLORS.cardBorder,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.03,
    shadowRadius: 8,
    elevation: 1,
  },
  cardHeading: {
    fontFamily: Fonts.cormorantGaramond.semiBold,
    fontSize: pt(19),
    lineHeight: pt(23),
    color: STATUS_COLORS.ink,
    letterSpacing: -0.2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 2,
  },

  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  statusCopy: {
    flex: 1,
    gap: 3,
  },
  statusTitle: {
    fontFamily: Fonts.cormorantGaramond.semiBold,
    fontSize: pt(22),
    lineHeight: pt(26),
    color: STATUS_COLORS.ink,
    letterSpacing: -0.3,
  },
  statusSubtitle: {
    fontFamily: Fonts.lexend.regular,
    fontSize: pt(11.5),
    lineHeight: pt(16),
    color: STATUS_COLORS.inkMuted,
  },
  statusDisc: {
    width: DISC.status,
    height: DISC.status,
    borderRadius: DISC.status / 2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  statusDiscDanger: {
    backgroundColor: STATUS_COLORS.dangerDiscBg,
    borderColor: STATUS_COLORS.dangerDiscBorder,
  },
  statusDiscSuccess: {
    backgroundColor: STATUS_COLORS.successDiscBg,
    borderColor: STATUS_COLORS.successDiscBorder,
  },
  statusDiscBrand: {
    backgroundColor: STATUS_COLORS.pendingDiscBg,
    borderColor: STATUS_COLORS.pendingDiscBorder,
  },
  statusRing: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: DISC.status / 2,
    borderWidth: 1,
  },
  errorStrip: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginTop: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: STATUS_COLORS.dangerAlertBg,
    borderWidth: 1,
    borderColor: STATUS_COLORS.dangerAlertBorder,
  },
  errorStripCopy: {
    flex: 1,
    fontFamily: Fonts.lexend.regular,
    fontSize: pt(11.5),
    lineHeight: pt(16),
    color: STATUS_COLORS.dangerAlertText,
  },
  rule: {
    marginTop: 14,
  },

  metaGroup: {
    marginTop: 12,
    gap: 10,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  metaLabel: {
    fontFamily: Fonts.lexend.regular,
    fontSize: pt(12.5),
    color: STATUS_COLORS.inkMuted,
  },
  metaValueWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 1,
  },
  metaValueText: {
    fontFamily: Fonts.lexend.medium,
    fontSize: pt(12.5),
    color: STATUS_COLORS.ink,
    flexShrink: 1,
    textAlign: 'right',
  },
  orderNumberText: {
    fontFamily: Fonts.lexend.semiBold,
    fontSize: pt(13),
    color: STATUS_COLORS.ink,
  },
  copyChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: STATUS_COLORS.well,
    borderWidth: 1,
    borderColor: STATUS_COLORS.wellBorder,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 3.5,
  },
  copyChipText: {
    fontFamily: Fonts.lexend.medium,
    fontSize: pt(10.5),
    color: STATUS_COLORS.inkSecondary,
  },
  divider: {
    height: 1,
    backgroundColor: STATUS_COLORS.divider,
    marginVertical: 12,
  },
  totalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 4,
  },
  totalLabel: {
    fontFamily: Fonts.lexend.medium,
    fontSize: pt(13.5),
    color: STATUS_COLORS.ink,
  },
  totalAmount: {
    fontFamily: Fonts.lexend.bold,
    fontSize: pt(18),
    color: STATUS_COLORS.darkGreen,
  },

  footerStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: STATUS_COLORS.well,
    borderTopWidth: 1,
    borderTopColor: STATUS_COLORS.cardBorder,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  footerStripCopy: {
    flex: 1,
    fontFamily: Fonts.lexend.regular,
    fontSize: pt(11),
    lineHeight: pt(15),
    color: STATUS_COLORS.inkSecondary,
  },

  bulletGroup: {
    paddingHorizontal: 18,
    paddingBottom: 10,
    marginTop: 4,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 9,
  },
  bulletIconDisc: {
    width: DISC.bullet,
    height: DISC.bullet,
    borderRadius: DISC.bullet / 2,
    backgroundColor: STATUS_COLORS.well,
    borderWidth: 1,
    borderColor: STATUS_COLORS.wellBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bulletCopy: {
    flex: 1,
    gap: 2,
  },
  bulletTitle: {
    fontFamily: Fonts.lexend.medium,
    fontSize: pt(12.5),
    color: STATUS_COLORS.ink,
  },
  bulletDesc: {
    fontFamily: Fonts.lexend.regular,
    fontSize: pt(11),
    lineHeight: pt(15),
    color: STATUS_COLORS.inkMuted,
  },
  bulletSeparator: {
    height: 1,
    backgroundColor: STATUS_COLORS.divider,
    marginLeft: DISC.bullet + 12,
  },

  supportRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
  },
  supportCopy: {
    flex: 1,
    gap: 2,
  },

  footerNote: {
    fontFamily: Fonts.lexend.regular,
    fontSize: pt(11),
    lineHeight: pt(15),
    color: STATUS_COLORS.inkFaint,
    textAlign: 'center',
    marginTop: 18,
    paddingHorizontal: 24,
    marginBottom: 6,
  },

  actionBar: {
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: STATUS_COLORS.cardBorder,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 3,
  },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: STATUS_COLORS.darkGreen,
    borderRadius: 25,
    height: 50,
    shadowColor: STATUS_COLORS.darkGreen,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 3,
  },
  primaryBtnText: {
    fontFamily: Fonts.lexend.medium,
    fontSize: pt(14),
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  ghostBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
  },
  ghostBtnText: {
    fontFamily: Fonts.lexend.medium,
    fontSize: pt(13),
    color: STATUS_COLORS.inkSecondary,
  },
});
