export const Fonts = {
    regular: 'Gilroy-Regular',
    medium: 'Gilroy-Medium',
    bold: 'Gilroy-Bold',
    semiBold: 'Gilroy-SemiBold',
    extraBold: 'Gilroy-ExtraBold',
    gilroyRegular: 'Gilroy-Regular',
    gilroyMedium: 'Gilroy-Medium',
    gilroySemiBold: 'Gilroy-SemiBold',
    gilroyBold: 'Gilroy-Bold',
    gilroyExtraBold: 'Gilroy-ExtraBold',
    gilroyLight: 'Gilroy-Light',
    poppins: {
        regular: 'Gilroy-Regular',
        medium: 'Gilroy-Medium',
        semiBold: 'Gilroy-SemiBold',
        bold: 'Gilroy-Bold',
        light: 'Gilroy-Light',
    },
};
