export const Fonts = {
    regular: 'CormorantGaramond-Regular',
    medium: 'CormorantGaramond-Medium',
    bold: 'CormorantGaramond-Bold',
    semiBold: 'CormorantGaramond-SemiBold',
    extraBold: 'CormorantGaramond-Bold',
    light: 'CormorantGaramond-Light',
    madelyn: 'Madelyn-Trial-Regular',
    madelynFill: 'MadelynFill-Trial-Regular',
    italic: 'CormorantGaramond-Italic',
    extraBoldItalic: 'CormorantGaramond-BoldItalic',
    lightItalic: 'CormorantGaramond-LightItalic',
    mediumItalic: 'CormorantGaramond-MediumItalic',
    gilroyRegular: 'CormorantGaramond-Regular',
    gilroyMedium: 'CormorantGaramond-Medium',
    gilroySemiBold: 'CormorantGaramond-SemiBold',
    gilroyBold: 'CormorantGaramond-Bold',
    gilroyExtraBold: 'CormorantGaramond-Bold',
    gilroyLight: 'CormorantGaramond-Light',
    lexend: {
        light: 'Lexend-Light',
        regular: 'Lexend-Regular',
        medium: 'Lexend-Medium',
        semiBold: 'Lexend-SemiBold',
        bold: 'Lexend-Bold',
    },
    poppins: {
        regular: 'CormorantGaramond-Regular',
        medium: 'CormorantGaramond-Medium',
        semiBold: 'CormorantGaramond-SemiBold',
        bold: 'CormorantGaramond-Bold',
        light: 'CormorantGaramond-Light',
    },
    cormorantGaramond: {
        light: 'CormorantGaramond-Light',
        lightItalic: 'CormorantGaramond-LightItalic',
        regular: 'CormorantGaramond-Regular',
        italic: 'CormorantGaramond-Italic',
        medium: 'CormorantGaramond-Medium',
        mediumItalic: 'CormorantGaramond-MediumItalic',
        semiBold: 'CormorantGaramond-SemiBold',
        semiBoldItalic: 'CormorantGaramond-SemiBoldItalic',
        bold: 'CormorantGaramond-Bold',
        boldItalic: 'CormorantGaramond-BoldItalic',
    }
};
