export const Fonts = {
    regular: 'Lexend-Regular',
    medium: 'Lexend-Medium',
    bold: 'Lexend-Bold',
    semiBold: 'Lexend-SemiBold',
    extraBold: 'Lexend-Bold',
    light: 'Lexend-Light',
    madelyn: 'Madelyn-Trial-Regular',
    madelynFill: 'MadelynFill-Trial-Regular',
    italic: 'Poppins-Italic',
    extraBoldItalic: 'Poppins-ExtraBoldItalic',
    lightItalic: 'Poppins-LightItalic',
    mediumItalic: 'Poppins-MediumItalic',
    gilroyRegular: 'Lexend-Regular',
    gilroyMedium: 'Lexend-Medium',
    gilroySemiBold: 'Lexend-SemiBold',
    gilroyBold: 'Lexend-Bold',
    gilroyExtraBold: 'Lexend-Bold',
    gilroyLight: 'Lexend-Light',
    lexend: {
        light: 'Lexend-Light',
        regular: 'Lexend-Regular',
        medium: 'Lexend-Medium',
        semiBold: 'Lexend-SemiBold',
        bold: 'Lexend-Bold',
    },
    poppins: {
        regular: 'Lexend-Regular',
        medium: 'Lexend-Medium',
        semiBold: 'Lexend-SemiBold',
        bold: 'Lexend-Bold',
        light: 'Lexend-Light',
    }
};
