import { StyleSheet } from 'react-native';
import {
  UI_COLORS,
  UI_ELEVATION,
  UI_RADIUS,
  UI_SPACING,
  hp,
  wp,
} from '../../theme/tokens';

export const detailsStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: UI_COLORS.canvas,
  },
  topContainer: {
    backgroundColor: UI_COLORS.card,
    paddingBottom: UI_SPACING.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: UI_COLORS.borderStrong,
    zIndex: 10,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: UI_SPACING.sm,
    paddingHorizontal: UI_SPACING.lg,
    paddingVertical: UI_SPACING.md,
  },
  backButton: {
    width: wp('9%'),
    height: wp('9%'),
    borderRadius: UI_RADIUS.pill,
    backgroundColor: UI_COLORS.well,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitleWrap: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: UI_SPACING.lg,
    paddingTop: UI_SPACING.lg,
    paddingBottom: hp('20%'),
    gap: UI_SPACING.lg,
  },

  card: {
    backgroundColor: UI_COLORS.card,
    borderRadius: UI_RADIUS.card,
    borderWidth: 1,
    borderColor: UI_COLORS.borderStrong,
    overflow: 'hidden',
  },
  cardPad: {
    padding: UI_SPACING.lg,
  },

  productRow: {
    flexDirection: 'row',
    gap: UI_SPACING.md,
    padding: UI_SPACING.lg,
  },
  productImageTile: {
    width: wp('22%'),
    height: wp('22%'),
    borderRadius: UI_RADIUS.productCard,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: UI_COLORS.border,
    backgroundColor: UI_COLORS.well,
    overflow: 'hidden',
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  productInfo: {
    flex: 1,
    justifyContent: 'center',
    gap: UI_SPACING.sm,
  },
  productMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: UI_SPACING.sm,
  },
  buyAgainBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: UI_SPACING.sm,
    marginHorizontal: UI_SPACING.lg,
    marginBottom: UI_SPACING.lg,
    height: hp('5.6%'),
    borderRadius: UI_RADIUS.button,
    borderWidth: 1,
    borderColor: UI_COLORS.primaryEdge,
    backgroundColor: UI_COLORS.primaryTint,
  },

  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: UI_SPACING.md,
    padding: UI_SPACING.lg,
  },
  statusInfo: {
    flex: 1,
    gap: UI_SPACING.xs,
  },
  trackBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: UI_SPACING.xs,
    paddingHorizontal: UI_SPACING.md,
    height: hp('4.6%'),
    borderRadius: UI_RADIUS.sm,
    borderWidth: 1,
    borderColor: UI_COLORS.primaryEdge,
    backgroundColor: UI_COLORS.primaryTint,
  },
  timeline: {
    paddingHorizontal: UI_SPACING.lg,
    paddingTop: UI_SPACING.lg,
    paddingBottom: UI_SPACING.xs,
  },
  timelineRow: {
    flexDirection: 'row',
    gap: UI_SPACING.md,
  },
  timelineRail: {
    alignItems: 'center',
    width: wp('7%'),
  },
  dotCurrent: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: UI_COLORS.primaryTint,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dotDone: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 8,
    backgroundColor: UI_COLORS.primary,
  },
  dotPending: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 8,
    borderWidth: 2,
    borderColor: UI_COLORS.borderStrong,
    backgroundColor: UI_COLORS.card,
  },
  railLineDone: {
    width: 2,
    flex: 1,
    marginVertical: UI_SPACING.xs,
    minHeight: hp('2.5%'),
    backgroundColor: UI_COLORS.primaryEdge,
  },
  railLinePending: {
    width: 2,
    flex: 1,
    marginVertical: UI_SPACING.xs,
    minHeight: hp('2.5%'),
    backgroundColor: UI_COLORS.border,
  },
  timelineBody: {
    flex: 1,
    paddingBottom: UI_SPACING.xl,
    gap: 2,
  },

  sectionHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: UI_SPACING.sm,
    paddingHorizontal: UI_SPACING.lg,
    paddingVertical: UI_SPACING.md,
  },
  thumbRow: {
    flexDirection: 'row',
    gap: UI_SPACING.md,
    padding: UI_SPACING.lg,
  },
  thumb: {
    width: wp('18%'),
    height: wp('18%'),
    borderRadius: UI_RADIUS.sm,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: UI_COLORS.border,
    backgroundColor: UI_COLORS.well,
    overflow: 'hidden',
  },
  thumbImage: {
    width: '100%',
    height: '100%',
  },

  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: UI_SPACING.md,
    paddingHorizontal: UI_SPACING.lg,
    paddingVertical: UI_SPACING.md,
  },

  addressRow: {
    flexDirection: 'row',
    gap: UI_SPACING.md,
    padding: UI_SPACING.lg,
  },
  addressBody: {
    flex: 1,
    gap: UI_SPACING.xs,
  },
  addressHeadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: UI_SPACING.sm,
  },

  retryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: UI_SPACING.sm,
    height: hp('6%'),
    borderRadius: UI_RADIUS.button,
    backgroundColor: UI_COLORS.primary,
  },

  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: UI_SPACING.md,
    backgroundColor: UI_COLORS.card,
    borderTopLeftRadius: UI_RADIUS.card + 8,
    borderTopRightRadius: UI_RADIUS.card + 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: UI_COLORS.borderStrong,
    paddingHorizontal: UI_SPACING.lg,
    paddingTop: UI_SPACING.lg,
    paddingBottom: hp('4%'),
    ...UI_ELEVATION.bar,
  },
  barGhostBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: UI_SPACING.sm,
    height: hp('6%'),
    borderRadius: UI_RADIUS.button,
    borderWidth: 1,
    borderColor: UI_COLORS.inkEdge,
    backgroundColor: UI_COLORS.card,
  },
  barGhostDanger: {
    borderColor: 'rgba(217,48,37,0.28)',
    backgroundColor: UI_COLORS.dangerTint,
  },
  barSolidBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: UI_SPACING.sm,
    height: hp('6%'),
    borderRadius: UI_RADIUS.button,
    backgroundColor: UI_COLORS.primary,
  },
});

export default detailsStyles;
