import { StyleSheet } from 'react-native';
import { Fonts } from '../../theme/fonts';
import {
  UI_GUTTER,
  UI_RADIUS,
  UI_SPACING,
  hp,
  wp,
} from '../../theme/tokens';

export const MAP_HEIGHT = hp('48%');
export const SHEET_TOP = hp('38%');
export const PIN_HEIGHT = wp('11%');
export const FIELD_HEIGHT = hp('6.2%');

const HAIRLINE = StyleSheet.hairlineWidth;

export const LUXURY_COLORS = {
  emerald: '#0C382E',
  emeraldLight: '#164E40',
  emeraldTint: '#E8F2EE',
  gold: '#B68D40',
  goldMetallic: '#C5A869',
  goldTint: '#FAF5EE',
  goldBorder: '#EFE7DB',
  canvas: '#FBFBFA',
  card: '#FFFFFF',
  border: '#ECEAE5',
  borderLight: '#F3F1ED',
  borderStrong: '#D6D2CA',
  textPrimary: '#1A1A1A',
  textSecondary: '#4A4A4A',
  textMuted: '#757575',
  textFaint: '#A0A0A0',
  well: '#FAF9F6',
  danger: '#D93025',
  dangerTint: '#FEF1F0',
  white: '#FFFFFF',
  overlay: 'rgba(12, 56, 46, 0.45)',
};

export default StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: LUXURY_COLORS.canvas,
  },
  flex: {
    flex: 1,
  },
  hidden: {
    display: 'none',
  },

  mapContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    width: '100%',
    height: MAP_HEIGHT,
  },
  map: {
    flex: 1,
  },

  pinWrap: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    top: MAP_HEIGHT / 2 - (PIN_HEIGHT + 6),
    zIndex: 10,
  },
  pinCallout: {
    position: 'absolute',
    bottom: PIN_HEIGHT + UI_SPACING.md,
    alignItems: 'center',
    paddingVertical: UI_SPACING.sm,
    paddingHorizontal: UI_SPACING.md + 4,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.goldBorder,
    backgroundColor: LUXURY_COLORS.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 6,
  },
  pinCalloutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  pinCalloutDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: LUXURY_COLORS.gold,
  },
  pinCalloutTitle: {
    fontFamily: Fonts.lexend?.semiBold || Fonts.gilroyBold,
    fontSize: 12,
    color: LUXURY_COLORS.textPrimary,
  },
  pinCalloutSubtitle: {
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 10.5,
    color: LUXURY_COLORS.textMuted,
    marginTop: 2,
  },
  pinCalloutHidden: {
    opacity: 0,
  },
  pinCalloutTail: {
    position: 'absolute',
    bottom: -5,
    width: 10,
    height: 10,
    borderRadius: 2,
    backgroundColor: LUXURY_COLORS.card,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: LUXURY_COLORS.goldBorder,
    transform: [{ rotate: '45deg' }],
  },
  pinIconContainer: {
    alignItems: 'center',
  },
  pinIcon: {
    height: PIN_HEIGHT,
  },
  pinIconLifted: {
    transform: [{ translateY: -10 }],
  },
  pinShadow: {
    width: 14,
    height: 5,
    borderRadius: 3,
    backgroundColor: 'rgba(0,0,0,0.22)',
    marginTop: -4,
  },
  pinShadowExpanded: {
    opacity: 0.1,
    transform: [{ scale: 0.7 }],
  },

  recenterButton: {
    position: 'absolute',
    bottom: MAP_HEIGHT - SHEET_TOP + UI_SPACING.lg,
    right: UI_GUTTER,
    flexDirection: 'row',
    alignItems: 'center',
    gap: UI_SPACING.xs + 2,
    paddingVertical: UI_SPACING.sm,
    paddingHorizontal: UI_SPACING.md,
    borderRadius: UI_RADIUS.pill,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.goldBorder,
    backgroundColor: LUXURY_COLORS.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 6,
    zIndex: 20,
  },
  recenterText: {
    fontFamily: Fonts.lexend?.medium || Fonts.gilroyMedium,
    fontSize: 12,
    color: LUXURY_COLORS.emerald,
  },

  overlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    paddingHorizontal: UI_GUTTER,
    zIndex: 999,
  },
  overlayRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  floatingButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.border,
    backgroundColor: LUXURY_COLORS.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 4,
  },
  searchLayer: {
    flex: 1,
    marginLeft: UI_SPACING.sm + 4,
    zIndex: 999,
  },
  searchIcon: {
    marginRight: UI_SPACING.sm,
  },
  geocodingBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
    gap: UI_SPACING.sm,
    marginTop: UI_SPACING.sm,
    paddingVertical: UI_SPACING.xs + 1,
    paddingHorizontal: UI_SPACING.md,
    borderRadius: UI_RADIUS.pill,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.goldBorder,
    backgroundColor: LUXURY_COLORS.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  geocodingText: {
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 11.5,
    color: LUXURY_COLORS.emerald,
  },

  sheet: {
    flex: 1,
    marginTop: SHEET_TOP,
    borderTopWidth: 1,
    borderTopColor: LUXURY_COLORS.border,
    paddingTop: UI_SPACING.sm + 2,
    backgroundColor: LUXURY_COLORS.card,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 8,
  },
  grabHandle: {
    width: wp('11%'),
    height: 4,
    borderRadius: UI_RADIUS.pill,
    backgroundColor: LUXURY_COLORS.borderStrong,
    alignSelf: 'center',
    marginBottom: UI_SPACING.xs,
  },
  sheetHeader: {
    paddingHorizontal: UI_GUTTER,
    paddingTop: UI_SPACING.sm,
    paddingBottom: UI_SPACING.md,
    borderBottomWidth: HAIRLINE,
    borderBottomColor: LUXURY_COLORS.border,
  },
  sheetTitle: {
    fontFamily: Fonts.cormorantGaramond?.bold || Fonts.bold,
    fontSize: 23,
    color: LUXURY_COLORS.emerald,
    letterSpacing: 0.3,
  },
  sheetSubtitle: {
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 12,
    color: LUXURY_COLORS.textMuted,
    marginTop: 3,
  },
  scroll: {
    flex: 1,
    paddingHorizontal: UI_GUTTER,
    backgroundColor: LUXURY_COLORS.canvas,
  },
  scrollContent: {
    paddingBottom: UI_SPACING.xl + 10,
  },

  resolvedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: UI_SPACING.md,
    padding: UI_SPACING.md + 2,
    marginTop: UI_SPACING.md + 2,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.goldBorder,
    backgroundColor: LUXURY_COLORS.goldTint,
  },
  resolvedIconBadge: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: LUXURY_COLORS.emeraldTint,
    borderWidth: 1,
    borderColor: 'rgba(12, 56, 46, 0.12)',
  },
  resolvedCopy: {
    flex: 1,
  },
  resolvedEyebrow: {
    fontFamily: Fonts.lexend?.semiBold || Fonts.gilroyBold,
    fontSize: 10,
    letterSpacing: 0.8,
    color: LUXURY_COLORS.gold,
    marginBottom: 3,
    textTransform: 'uppercase',
  },
  resolvedAddressMain: {
    fontFamily: Fonts.lexend?.semiBold || Fonts.gilroyBold,
    fontSize: 13.5,
    lineHeight: 18,
    color: LUXURY_COLORS.textPrimary,
  },
  resolvedLine2: {
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 12,
    lineHeight: 16,
    color: LUXURY_COLORS.textMuted,
    marginTop: 3,
  },

  sectionCard: {
    marginTop: UI_SPACING.md,
    paddingTop: UI_SPACING.md + 4,
    paddingBottom: UI_SPACING.sm,
    paddingHorizontal: UI_SPACING.md + 2,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.border,
    backgroundColor: LUXURY_COLORS.card,
  },
  sectionTitleWrap: {
    marginBottom: UI_SPACING.md + 2,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sectionTitleBar: {
    width: 3.5,
    height: 15,
    borderRadius: 2,
    backgroundColor: LUXURY_COLORS.emerald,
    marginRight: UI_SPACING.sm,
  },
  sectionTitleText: {
    fontFamily: Fonts.cormorantGaramond?.bold || Fonts.bold,
    fontSize: 18,
    color: LUXURY_COLORS.emerald,
    letterSpacing: 0.2,
  },
  sectionTitleHint: {
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 11.5,
    color: LUXURY_COLORS.textMuted,
    marginTop: 2,
    marginLeft: UI_SPACING.md + 2,
  },

  typeRow: {
    flexDirection: 'row',
    gap: UI_SPACING.sm,
    marginBottom: UI_SPACING.sm + 2,
  },
  typeChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: UI_SPACING.xs + 2,
    minHeight: hp('5.4%'),
    paddingHorizontal: UI_SPACING.sm,
    paddingVertical: UI_SPACING.sm,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.border,
    backgroundColor: LUXURY_COLORS.well,
  },
  typeChipActive: {
    borderWidth: 1.4,
    borderColor: LUXURY_COLORS.emerald,
    backgroundColor: LUXURY_COLORS.emeraldTint,
  },
  typeChipLabel: {
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 12.5,
    color: LUXURY_COLORS.textMuted,
  },
  typeChipLabelActive: {
    fontFamily: Fonts.lexend?.semiBold || Fonts.gilroyBold,
    color: LUXURY_COLORS.emerald,
  },

  fieldWrapper: {
    marginBottom: UI_SPACING.md + 4,
    position: 'relative',
  },
  fieldLabel: {
    position: 'absolute',
    top: -hp('0.95%'),
    left: UI_SPACING.md,
    zIndex: 2,
    paddingHorizontal: UI_SPACING.xs + 2,
    backgroundColor: LUXURY_COLORS.card,
    fontFamily: Fonts.lexend?.medium || Fonts.gilroyMedium,
    fontSize: 11,
    lineHeight: 15,
    includeFontPadding: false,
    textAlignVertical: 'center',
    paddingVertical: 1,
    color: LUXURY_COLORS.textMuted,
    borderRadius: 4,
  },
  fieldLabelActive: {
    color: LUXURY_COLORS.emerald,
    fontFamily: Fonts.lexend?.semiBold || Fonts.gilroyBold,
  },
  fieldLabelError: {
    color: LUXURY_COLORS.danger,
  },
  fieldRequired: {
    color: LUXURY_COLORS.danger,
  },
  input: {
    minHeight: FIELD_HEIGHT,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.border,
    borderRadius: 12,
    backgroundColor: LUXURY_COLORS.well,
    paddingHorizontal: UI_SPACING.md + 2,
    paddingVertical: UI_SPACING.sm,
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 13.5,
    color: LUXURY_COLORS.textPrimary,
  },
  inputFocused: {
    borderWidth: 1.4,
    borderColor: LUXURY_COLORS.emerald,
    backgroundColor: LUXURY_COLORS.card,
  },
  landmarkInput: {
    minHeight: hp('8.2%'),
    textAlignVertical: 'top',
    paddingTop: UI_SPACING.sm + 2,
  },

  pincodeRow: {
    flexDirection: 'row',
    gap: UI_SPACING.md,
    zIndex: 10,
  },
  pincodeField: {
    flex: 1,
  },
  areaWrap: {
    flex: 1,
    marginBottom: UI_SPACING.md + 4,
    position: 'relative',
  },
  areaLabel: {
    zIndex: 7000,
  },
  areaTrigger: {
    minHeight: FIELD_HEIGHT,
    flexDirection: 'row',
    alignItems: 'center',
    gap: UI_SPACING.sm,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.border,
    borderRadius: 12,
    paddingHorizontal: UI_SPACING.md + 2,
    backgroundColor: LUXURY_COLORS.well,
  },
  areaTriggerOpen: {
    borderWidth: 1.4,
    borderColor: LUXURY_COLORS.emerald,
    backgroundColor: LUXURY_COLORS.card,
  },
  areaTriggerLabel: {
    flex: 1,
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 13.5,
    color: LUXURY_COLORS.textPrimary,
  },
  areaTriggerPlaceholder: {
    color: LUXURY_COLORS.textFaint,
  },

  areaSheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: LUXURY_COLORS.overlay,
  },
  areaSheetDismiss: {
    flex: 1,
  },
  areaSheet: {
    maxHeight: hp('72%'),
    paddingTop: UI_SPACING.sm,
    backgroundColor: LUXURY_COLORS.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 10,
  },
  areaSheetGrab: {
    width: wp('11%'),
    height: 4,
    alignSelf: 'center',
    borderRadius: UI_RADIUS.pill,
    backgroundColor: LUXURY_COLORS.borderStrong,
  },
  areaSheetHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingTop: UI_SPACING.md,
    paddingBottom: UI_SPACING.md,
    paddingHorizontal: UI_GUTTER,
    borderBottomWidth: HAIRLINE,
    borderBottomColor: LUXURY_COLORS.border,
  },
  areaSheetHeadline: {
    flex: 1,
  },
  areaSheetTitle: {
    fontFamily: Fonts.cormorantGaramond?.bold || Fonts.bold,
    fontSize: 21,
    color: LUXURY_COLORS.emerald,
    letterSpacing: 0.3,
  },
  areaSheetContext: {
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 12,
    color: LUXURY_COLORS.textMuted,
    marginTop: 2,
  },
  areaSheetClose: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: LUXURY_COLORS.well,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.border,
  },

  areaSearch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: UI_SPACING.sm,
    marginTop: UI_SPACING.md,
    marginHorizontal: UI_GUTTER,
    paddingHorizontal: UI_SPACING.md,
    minHeight: hp('5.4%'),
    borderRadius: 12,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.border,
    backgroundColor: LUXURY_COLORS.well,
  },
  areaSearchInput: {
    flex: 1,
    paddingVertical: UI_SPACING.sm,
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 13.5,
    color: LUXURY_COLORS.textPrimary,
  },

  areaList: {
    flexGrow: 0,
  },
  areaListContent: {
    paddingTop: UI_SPACING.md,
    paddingBottom: UI_SPACING.lg,
    paddingHorizontal: UI_GUTTER,
  },
  areaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: UI_SPACING.md,
    minHeight: hp('6.2%'),
    marginBottom: UI_SPACING.sm,
    paddingVertical: UI_SPACING.sm + 4,
    paddingHorizontal: UI_SPACING.md + 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.border,
    backgroundColor: LUXURY_COLORS.well,
  },
  areaRowSelected: {
    borderWidth: 1.4,
    borderColor: LUXURY_COLORS.emerald,
    backgroundColor: LUXURY_COLORS.emeraldTint,
  },
  areaRowLabel: {
    flex: 1,
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 13.5,
    color: LUXURY_COLORS.textPrimary,
  },
  areaRowLabelSelected: {
    fontFamily: Fonts.lexend?.semiBold || Fonts.gilroyBold,
    color: LUXURY_COLORS.emerald,
  },
  areaSheetState: {
    alignItems: 'center',
    gap: UI_SPACING.sm,
    paddingVertical: UI_SPACING.xxl,
    paddingHorizontal: UI_GUTTER,
  },
  areaSheetStateTitle: {
    fontFamily: Fonts.lexend?.semiBold || Fonts.gilroyBold,
    fontSize: 14,
    color: LUXURY_COLORS.textPrimary,
    textAlign: 'center',
  },
  areaSheetStateText: {
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 13,
    color: LUXURY_COLORS.textMuted,
    textAlign: 'center',
  },

  footer: {
    paddingHorizontal: UI_GUTTER,
    paddingTop: UI_SPACING.md,
    borderTopWidth: 1,
    borderTopColor: LUXURY_COLORS.border,
    backgroundColor: LUXURY_COLORS.card,
  },
  saveButton: {
    height: hp('6.5%'),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: UI_SPACING.sm,
    borderRadius: 14,
    backgroundColor: LUXURY_COLORS.emerald,
    shadowColor: LUXURY_COLORS.emerald,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    elevation: 5,
  },
  saveButtonBusy: {
    opacity: 0.75,
  },
  saveButtonText: {
    fontFamily: Fonts.lexend?.bold || Fonts.gilroyBold,
    fontSize: 15,
    color: LUXURY_COLORS.white,
    letterSpacing: 0.3,
  },
});

export const placesStyles = {
  container: { flex: 0 },
  textInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: FIELD_HEIGHT,
    paddingHorizontal: UI_SPACING.md,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.border,
    backgroundColor: LUXURY_COLORS.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  textInput: {
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 13.5,
    color: LUXURY_COLORS.textPrimary,
    height: FIELD_HEIGHT,
    flex: 1,
    paddingVertical: 0,
    paddingHorizontal: 0,
    backgroundColor: 'transparent',
  },
  description: {
    fontFamily: Fonts.lexend?.regular || Fonts.gilroyRegular,
    fontSize: 13,
    color: LUXURY_COLORS.textSecondary,
  },
  listView: {
    position: 'absolute',
    top: FIELD_HEIGHT + 6,
    width: '100%',
    zIndex: 9999,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: LUXURY_COLORS.border,
    backgroundColor: LUXURY_COLORS.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 10,
    elevation: 8,
    overflow: 'hidden',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: hp('6%'),
    paddingHorizontal: UI_SPACING.lg,
    paddingVertical: UI_SPACING.md,
    backgroundColor: LUXURY_COLORS.card,
  },
  separator: {
    height: HAIRLINE,
    backgroundColor: LUXURY_COLORS.border,
  },
  loader: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    height: 20,
  },
};
